language: c
before_install:
  - sudo apt-get install valgrind
install:
  - sudo make install gcov --file=linux.makefile
script:
  - cd ./example01 && cp -f ../linux_test.makefile ./makefile && make valgrind      && cd .. 
  - cd ./example02 && cp -f ../linux_test.makefile ./makefile && make valgrind      && cd ..
  - cd ./test      && cp -f ../linux_test.makefile ./makefile && make all gcov valgrind
after_success:
  - bash <(curl -s https://codecov.io/bash)