language: c
before_install:
install:
  - sudo apt-get install valgrind
  - sudo make install --file=linux.makefile
script:
  - cd example01
  - make valgrind --file=linux.makefile
  - cd .. 
  - cd example02
  - make valgrind --file=linux.makefile
  - cd ..
  - cd test
  - make valgrind --file=linux.makefile
after_success:
  - bash <(curl -s https://codecov.io/bash)