language: c
before_install:
install:
  - sudo apt-get install valgrind
  - sudo make install --file=linux.makefile
script:
  - cd example01
  - make valgrind --file=linux.makefile
  - cd .. 
  - cd example02
  - make valgrind --file=linux.makefile
  - cd ..
after_script: