language: c
before_install:
install:
  - sudo make install --file=linux.makefile
script:
  - cd example01
  - make run --file=linux.makefile
  - cd example02
  - make run --file=linux.makefile
after_script: